### ISSUE TITLE
Research on how to interact with the manager GUI

### ISSUE THREAD

**Issue by ivcosla** [skycoin/skywire-testnet#173]
In order to integrate new services with the manager GUI we need to know how to do and where to place the code for the following operations over `http`:
1) How can a external service request the manager to pop up a window asking for user interaction
2) How can we call back one of our services when the user has interacted with it

**Comment by alimasyhur** [comment]
## Step to produce
1. Create an API to handle incoming data/event from external services
2. In the frontend side: listen in the websocket
3. If any incoming new event from external service, api will send it to the websocket. Frontend side will ask user to interact with it by showing popup window (example: update particular external service).
4. Handle user interaction and process user request by creating new API.

### Where to Place Code
1. **Create check external service update NodeAPI in package api: `/node/run/checkExternalServiceUpdate`**
    **path** : `pkg/node/api/api.go`
    **usage** : get incoming data from external services
    **return** : data if any new event(update) from external service

2. **Register ApiService in Frontend Side**
    Usage
    If there is a new event from websocket, frontend side will show popup window about the event info to the user
    ```
    checkExternalServiceUpdate(addr: string) {
        return this.handleReq(addr, '/node/run/checkExternalServiceUpdate');
    }
    ```
    
3. **User interacts with external service request if `checkExternalServiceUpdate` endpoints returned external service data**

4. **Create check external service update NodeAPI in package api: `/node/run/externalServiceUpdate`**
    **path** : `pkg/node/api/api.go`
    **param** : token or id or name of external services
    **usage** : run updating external services request
    **return** : status processed external service request
    
    These steps are accomplished by pre and post scripts that probably similar as described on this image below.
![alt text](https://windowspackager.org/sites/windowspackager.org/files/images/Scripts-UpgradeInstallation_0.png "Update External Service Request")

    Communication between client&server are using websocket. whether updating process success or not, the frontend will know the progress/status.
    
5. **Package external service request may located in `pkg/net/skycoin-external-service`** and follow like skycoin-manager gui

**Comment by ivcosla** [comment]
Good job so far.

In order for `updater` to report the status of the update we may need an additional endpoint. For communication between client & server I really prefer an HTTP API Gateway instead of a websocket. If it is much easier for you to implement it as a websocket let me know how to communicate with it in order to notify that a new version is available or that update has been succesful or failed, etc.

**Comment by alimasyhur** [comment]
I also think better use API Gateway Architecture, because if we enlarge our application into Multiplatform: web app, desktop app, and mobile app, and I was thinking to implement API Gateway that is single entry point for all clients

```
Web App —> webapp API Gateway —> endpoints of external services
Mobile App —> mobile API Gateway —> endpoints of external services
3rd party Apps —> public API Gateway —> endpoints of external services
```

Each of API Gateway provides an API for its client.

In order for updater to report of the external services update. we should notify user asynchronously that there is an update of the particular external service.
Let’s say there’s an update of API Gateway v.1 to v2 with some additional enhancements, API Gateway provides an api and notify them that there’s new service update by comparing user’s api version with the latest API Gateway version.

User confirms that they want to subscribe new service update. 
_I was thinking that if user uses web app, no need user confirmation. System will show that there was an system/service update, this is called **auto-updater**. In the other hand, If user uses desktop/mobile app, user will receive notification in order to update their app._
User data may look like this, example:
```
{
	“access_token” : “<token>”,
	“device_type” : “webapp”,
	"api_info" : {
	    "key" : "<api_key>",
	    "version" : "1.0"
	}
}
```

API Gateway sends response data that may look like below:
```
{
	“access_token” : “<token>”,
	“device_type” : “webapp”,
	“status_update” : true,
	“message”: “Changelog Message. Additional message about service update”,
	"api_info" : {
	    "key" : "<api_key>",
	    “old_version” : “1.0”,
	    “new_version” : “2.0”,
	}
}
```

System also update user data that user has subscribed new version api.

If there was an error while updating service, the response may look like this:
```
{
	"access_token” : “<token>”, \n
	“device_type” : “webapp”,
	“status_update” : false,
	“message”: “There were an error updating services: ….”
	"api_info" : {
	    "key" : "<api_key>",
	    “old_version” : “1.0”,
            “new_version” : “2.0”,
	},
}
```

There will be one `updater` instance deployed in every node that has a service registered with the manager ui
