### ISSUE TITLE
Change behaviour of how skywire-node finds config file.

### ISSUE THREAD

**Issue by evanlinjin** [skycoin/skywire-testnet#205]
Should check for config file in this order:
1. CLI argument (if specified, directly use this. Return error if not valid).
2. Environment variable (env prefix for Skywire should be `SW`. If set and not valid, return error).
3. Uses `~/.skycoin/skywire/config.json` if exists.
4. Uses `/usr/local/skycoin/skywire/config.json` if exists.

Similar behavior should happen for apps, app-configs and database files too. This can be defined later on.

**Comment by gz-c** [comment]
I prefer this order:

1. CLI flag
2. Environment variable
3. Home directory folder
4. System directory folder

CLI flag and envvar are a toss up; since it can be difficult to check if the user provided the CLI flag or not, it could be easier to make an env var take priority, since its obvious to check if provided or not (check if empty string).

Or, if nobody has a need for an env var, don't use env vars at all.  But `~/.skycoin/skywire/config.json` should take precendence over `/usr/local/skycoin/skywire/config.json`

**Comment by evanlinjin** [comment]
> I prefer this order:
> 
>     1. CLI flag
> 
>     2. Environment variable
> 
>     3. Home directory folder
> 
>     4. System directory folder
> 
> 
> CLI flag and envvar are a toss up; since it can be difficult to check if the user provided the CLI flag or not, it could be easier to make an env var take priority, since its obvious to check if provided or not (check if empty string).
> 
> Or, if nobody has a need for an env var, don't use env vars at all. But `~/.skycoin/skywire/config.json` should take precendence over `/usr/local/skycoin/skywire/config.json`

Updated.

**Comment by ivcosla** [comment]
Closed in #208
